#!/usr/bin/env bash
#
# Phalcon Box
#
# Copyright (c) 2011-2017, Phalcon Framework Team
#
# The contents of this file are subject to the New BSD License that is
# bundled with this package in the file LICENSE.txt
#
# If you did not receive a copy of the license and are unable to obtain it
# through the world-wide-web, please send an email to license@phalconphp.com
# so that we can send you a copy immediately.
#

# trace ERR through pipes
set -o pipefail

# trace ERR through 'time command' and other functions
set -o errtrace

# set -u : exit the script if you try to use an uninitialised variable
set -o nounset

# set -e : exit the script if any statement returns a non-true return value
set -o errexit

CURRENT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if [ -f "${CURRENT_DIR}/src/templates/settings.yml" ]; then
	cp -n "${CURRENT_DIR}/src/templates/settings.yml" "${CURRENT_DIR}/settings.yml"
fi

if [ -f "${CURRENT_DIR}/src/templates/after_provision.sh" ]; then
	cp -n "${CURRENT_DIR}/src/templates/after_provision.sh" "${CURRENT_DIR}/after_provision.sh"
fi

if [ -f "${CURRENT_DIR}/src/templates/.bash_aliases" ]; then
	cp -n "${CURRENT_DIR}/src/templates/.bash_aliases" "${CURRENT_DIR}/.bash_aliases"
fi

echo -ne "\nPhalcon Box initialized\n"
