#!/bin/bash
#
# Phalcon Box
#
# Copyright (c) 2011-2017, Phalcon Framework Team
#
# The contents of this file are subject to the New BSD License that is
# bundled with this package in the file LICENSE.txt
#
# If you did not receive a copy of the license and are unable to obtain it
# through the world-wide-web, please send an email to license@phalconphp.com
# so that we can send you a copy immediately.
#

PURPLE="\033[0;35m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
NC="\033[0m"

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "\$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION=\$(lsb_release -s -d)
fi

read -d '' banner <<"BLOCK"
    Thank you for using Phalcon Box!
    We hope that Phalcon Box helps to make your life easier.

    In case of problems:    https://github.com/phalcon/box/issues
    Questions should go to: https://forum.phalconphp.com
    Documentation:          https://docs.phalconphp.com
BLOCK

printf "\n"
printf "    \${YELLOW}Welcome to Phalcon Box\${NC}\n"
printf "\n"
printf "    Phalcon Box:            %s\n" \$(cd /vagrant; git describe --tags --abbrev=0)
printf "    Distrib:                %s (%s %s %s)\n" "\$DISTRIB_DESCRIPTION" "\$(uname -o)" "\$(uname -r)" "\$(uname -m)"
printf "    Zephir:                 v%s\n" \$(zephir version)
printf "    PHP:                    v%s\n" \$(php -v | head -n 1 | cut -d ' ' -f 2 | cut -d '-' -f 1)
printf "    Phalcon Framework:      v%s\n" \$(php -r 'echo Phalcon\Version::get();')
printf "\n"
printf "    %s" "\$banner"
printf "\n\n"

